// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2/3/2026, 3:13:30 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/home/ra/Documents/favilances.pages.dev/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/ra/Documents/favilances.pages.dev/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/ra/Documents/favilances.pages.dev/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/ra/Documents/favilances.pages.dev/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/ra/Documents/favilances.pages.dev/plugins/**/*.{js,ts,mjs}","/home/ra/Documents/favilances.pages.dev/composables/**/*.{js,ts,mjs}","/home/ra/Documents/favilances.pages.dev/utils/**/*.{js,ts,mjs}","/home/ra/Documents/favilances.pages.dev/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/ra/Documents/favilances.pages.dev/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/ra/Documents/favilances.pages.dev/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/ra/Documents/favilances.pages.dev/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = (() => {const cfg=config;cfg["content"]["files"]["17"] = "/home/ra/Documents/favilances.pages.dev/.nuxt/content-cache/parsed/**/*.{md,yml,yaml,json}";;return cfg;})();

export default resolvedConfig;